### ISSUE TITLE
大佬，请求批量处理功能

### ISSUE THREAD

**Issue by tpnet** [YaoFANGUK/video-subtitle-remover#12]
大佬，很多视频的情况下，一个个处理太低效率了，可以选择文件处理全部视频吗？

**Comment by MuDong612** [comment]
请问代码运行怎么批量处理啊，怎么打开视频多选功能

**Comment by YaoFANGUK** [comment]
> 请问代码运行怎么批量处理啊，怎么打开视频多选功能


你点击open后多选几个视频就是批量

**Comment by MuDong612** [comment]
我用命令行运行的main.py，用不了Gui，这个怎么才能多选视频啊

**Comment by YaoFANGUK** [comment]
你自己开多进程，不会就看看gui.py里面的代码

**Comment by tpnet** [comment]
@MuDong612  命令行的方式，我是自己改了代码，传入文件夹路径的方式去轮询处理。

**Comment by MuDong612** [comment]
@tpnet 大佬可以分享一下代码吗，急需

**Comment by tpnet** [comment]
> @tpnet 大佬可以分享一下代码吗，急需

我之前用的旧版的代码改的，新版还没更新，你自己gpt问一下就好了，很简单的。

**Comment by MuDong612** [comment]
@tpnet 好的谢谢
