### ISSUE TITLE
It seems didn't use the GPU, but only use about 10%CPU,how to fix it?

### ISSUE THREAD

**Issue by Xiao177** [YaoFANGUK/video-subtitle-remover#2]
Hi, it is a great video_subtitle_remover. But it cost a lot of time to finish in my  computer. I need some help.
`
F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr>"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');from qpt.run import module;module.run('""')"
F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr\Python\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
→[2023-10-28 15:28:29,409] [WARNING] | C:\Users\XIAOYU~1\AppData\Local\Temp\QPT_Cache_V/1.0b4.dev6中 ~ 字符会可能影响使用。
→[2023-10-28 15:28:29,410] [WARNING] | 当前系统的用户名中包含中文/空格等可能会对程序造成异常的字符，现已默认QPT临时目录为C:/q_tmp
→[2023-10-28 15:28:29,573] [INFO] | QPT Runtime版本号为1.0b4.dev6，若无法使用该 程序，可向程序发布者或GitHub: QPT-Family/QPT提交issue寻求帮助
→[2023-10-28 15:28:30,179] [INFO] | 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度28 15:1/7  |━━                  | 14.29% AutoPythonEnv部署中...→[2023-
初始化进度8:30,12/7  |━━━━━               | 28.57% QPTDependencyPackage部署中...
初始化进度28 15:3/7  |━━━━━━━━            | 42.86% CopyCUDAPackage部署中...→[202
初始化进度:28:304/7  |━━━━━━━━━━━         | 57.14% NoneName_paddlepaddle-gpu部署
初始化进度3-10-25/7  |━━━━━━━━━━━━━━      | 71.43% AutoRequirementsPackage部署中
初始化进度10-28 6/7  |━━━━━━━━━━━━━━━━━   | 85.71% 初始化完毕→[2023-10-28 15:28:30,192] [INFO] | ----------WARNING SUMMARY
→[2023-10-28 15:28:30,192] [INFO] | 0|C:\Users\XIAOYU~1\AppData\Local\Temp\QPT_Cache_V/1.0b4.dev6中 ~ 字符会可能影响使用。

→[2023-10-28 15:28:30,193] [INFO] | 1|当前系统的用户名中包含中文/空格等可能会对 程序造成异常的字符，现已默认QPT临时目录为C:/q_tmp

→[2023-10-28 15:28:30,193] [INFO] | ----------ERROR SUMMARY
→[2023-10-28 15:28:30,193] [INFO] | ----------生成状态WARNING:2 ERROR:0
PS F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr> cd "F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr\resources";./../Python/python.exe "F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr\resources\gui.py"  ; echo "---QPT OUTPUT STATUS CODE---" $?
F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr\Python\Lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
F:\Video_subtitle_remover\vsr_windows_gpu_v1.0.0\vsr\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Running Verify Fluid Program ...
W1028 15:28:34.698318  3128 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.3, Runtime API Version: 11.7
W1028 15:28:34.698318  3128 gpu_resources.cc:91] device: 0, cuDNN Version: 8.5.
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
1707 1067
Subtitle Finding: 100%|██████████| 125/125 [00:10<00:00, 12.35f/s]
Subtitle Removing: 100%|██████████| 125/125 [04:46<00:00,  2.29s/f]
` 
There are a lots of warnings in my environment. I used the release one. It looks like Nvidia 3070 didn't work for it. Is there any idea to solve it? Thank u very much.

**Comment by YaoFANGUK** [comment]
要打印use gpu for acceleration才证明使用的gpu

**Comment by Xiao177** [comment]
Ok, thank you. But I only have this sentence on the GUI.
<img width="495" alt="image" src="https://github.com/YaoFANGUK/video-subtitle-remover/assets/116617166/971160a8-a7a3-4ae9-ae22-9c2fe267a198">

**Comment by YaoFANGUK** [comment]
its running please wait

**Comment by Xiao177** [comment]
Awesome! Thanks a lot!
