### ISSUE TITLE
新安装包解压有个文件出错了

### ISSUE THREAD

**Issue by seetimee** [YaoFANGUK/video-subtitle-remover#21]
![image](https://github.com/YaoFANGUK/video-subtitle-remover/assets/50852027/d30fc3f1-0791-41c0-8aa1-faa3e87ba31f)

**Comment by seetimee** [comment]
是github  release里面的分包,我再试下谷歌硬盘里的整合包有没有问题

**Comment by huangyan20** [comment]
包没下完整，重新下，换个梯子或者去gitee上旧版的先玩玩

**Comment by YaoFANGUK** [comment]
> 是github release里面的分包,我再试下谷歌硬盘里的整合包有没有问题

你001,002,003 三个分卷都下载了吗

**Comment by seetimee** [comment]
整合包运行成功了,速度比之前快了4倍,但是去除的效果很差

**Comment by seetimee** [comment]
![image](https://github.com/YaoFANGUK/video-subtitle-remover/assets/50852027/7e499758-d99d-4016-8c5b-3d579976d2d0)

**Comment by seetimee** [comment]
![image](https://github.com/YaoFANGUK/video-subtitle-remover/assets/50852027/99719c5f-ca46-49e9-8feb-114c712ed91b)

**Comment by YaoFANGUK** [comment]
很差建议卸载别用

**Comment by YaoFANGUK** [comment]
不会调参数就卸载吧 config.py里都备注了的

**Comment by seetimee** [comment]
不好意思大佬,我去学习下config
