### ISSUE TITLE
[Solved] 找不到PySimpleGUI

### ISSUE THREAD

**Issue by LeonCheung** [YaoFANGUK/video-subtitle-remover#49]
请问这种问题怎么解决，明明装了的：
![image](https://github.com/YaoFANGUK/video-subtitle-remover/assets/494788/fcefdafa-473b-494e-8d69-6e459f3d1057)

**Comment by LeonCheung** [comment]
已解决。原来是之前C盘容量不够，导致下载不完全。没想到安装居然还需要好几个G的空间...

**Comment by Jumao-OC** [comment]
> 已解决。原来是之前C盘容量不够，导致下载不完全。没想到安装居然还需要好几个G的空间...

你是怎么下载的 我这里为什么报错(videoEnvTwo) D:\test\video-subtitle-remover\video-subtitle-remover-main>pip install PySimpleGUI==4.70.1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement PySimpleGUI==4.70.1 (from versions: 5.0.8.2)
ERROR: No matching distribution found for PySimpleGUI==4.70.1
