### ISSUE TITLE
ModuleNotFoundError: No module named 'fsplit'

### ISSUE THREAD

**Issue by ryouxin** [YaoFANGUK/video-subtitle-remover#77]
运行python ./backend/main.py 的时候遇到这个问题 经过查询安装了 pip install filesplit 也不行

**Comment by kami233** [comment]
> 运行python ./backend/main.py 的时候遇到这个问题 经过查询安装了 pip install filesplit 也不行

要运行它自己文件夹里面那个python才行，安装你本地环境的那个python没用的

**Comment by ryouxin** [comment]
> > 运行python ./backend/main.py 的时候遇到这个问题 经过查询安装了 pip install filesplit 也不行
> 
> 要运行它自己文件夹里面那个python才行，安装你本地环境的那个python没用的

没明白 我看他仓库里面也没有python可执行文件

**Comment by danielchan-25** [comment]
@kami233 @ryouxin 两位大哥解决了吗？"运行它自己文件夹里面的那个python" 是啥意思？没看明白

**Comment by NOMIzy** [comment]
pip install filesplit==3.0.1
