### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Pahkho** [YaoFANGUK/video-subtitle-remover#90]
→[2024-09-17 17:20:15,738] [ERROR] | 在执行终端命令时检测到了失败，完整信息如下：
PS G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr> cd "G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\resources";./../Python/python.exe "G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\resources\gui.py"  ; echo "---QPT OUTPUT STATUS CODE---" $?
G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\Python\Lib\site-packages\setuptools\sandbox.p:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Traceback (most recent call last):
  File "G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\resources\gui.py", line 17, in <module>
    import backend.main
  File "G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\resources\backend\main.py", line 10, in <module>
    import config
  File "G:\video-subtitle\vsr_windows_gpu_v1.1.0-001\vsr\resources\backend\config.py", line 17, in <module>
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
AttributeError: module 'torch' has no attribute 'device'

**Comment by Pahkho** [comment]
...

**Comment by Socksar** [comment]
> ...

请问这个是什么原因，应该怎么解决？
